import jsPDF from "jspdf";
import { formatCurrencyWithCents } from "@/lib/utils";

// Re-export sections type from schema for convenience
export type { AccountantPackSections } from "@/server/db/schema/portfolio";

export interface AccountantPackConfig {
  financialYear: number;
  userName: string;
  accountantName?: string;
  sections: {
    incomeExpenses: boolean;
    depreciation: boolean;
    capitalGains: boolean;
    taxPosition: boolean;
    portfolioOverview: boolean;
    loanDetails: boolean;
  };
  data: {
    taxReport?: TaxReportData;
    myTaxReport?: MyTaxReportData;
    cgtData?: CgtPropertyResult[];
    taxPosition?: TaxPositionData;
    portfolioSnapshot?: PortfolioSnapshotData;
    loanPackSnapshot?: LoanPackSnapshotData;
  };
}

// Minimal types for the data we actually use from existing services.
// Kept lean — don't import full service types to avoid circular deps with server code.
interface TaxReportData {
  financialYear: string;
  startDate: string;
  endDate: string;
  properties: Array<{
    property: {
      id: string;
      address: string;
      suburb: string;
      state: string;
      entityName: string | null;
    };
    metrics: {
      totalIncome: number;
      totalExpenses: number;
      netIncome: number;
      totalDeductible: number;
    };
    atoBreakdown: Array<{
      category: string;
      label: string;
      amount: number;
      atoReference: string | null | undefined;
      isDeductible: boolean;
    }>;
    transactionCount: number;
  }>;
  totals: {
    totalIncome: number;
    totalExpenses: number;
    netIncome: number;
    totalDeductible: number;
  };
  generatedAt: string;
}

interface MyTaxReportData {
  financialYear: string;
  properties: Array<{
    address: string;
    suburb: string;
    state: string;
    entityName: string;
    income: Array<{ label: string; amount: number; atoCode?: string }>;
    deductions: Array<{ label: string; amount: number; atoCode?: string }>;
    depreciation: { capitalWorks: number; plantEquipment: number };
    totalIncome: number;
    totalDeductions: number;
    netResult: number;
  }>;
}

interface CgtPropertyResult {
  propertyAddress: string;
  purchaseDate: string;
  saleDate: string;
  costBase: number;
  salePrice: number;
  capitalGain: number;
  discountedGain: number;
  heldOverTwelveMonths: boolean;
}

interface TaxPositionData {
  taxableIncome: number;
  baseTax: number;
  medicareLevy: number;
  medicareLevySurcharge: number;
  hecsRepayment: number;
  totalTaxLiability: number;
  paygWithheld: number;
  refundOrOwing: number;
  isRefund: boolean;
  marginalRate: number;
  propertySavings: number;
}

interface PortfolioSnapshotData {
  properties: Array<{
    address: string;
    suburb: string;
    state: string;
    purchasePrice: number;
    currentValue: number;
    equity: number;
    lvr: number;
  }>;
  totals: {
    totalValue: number;
    totalDebt: number;
    totalEquity: number;
    avgLvr: number;
    propertyCount: number;
  };
}

interface LoanPackSnapshotData {
  properties: Array<{
    address: string;
    loans: Array<{
      lender: string;
      balance: number;
      rate: number;
      type: string;
      monthlyRepayment: number;
    }>;
  }>;
  totals: {
    totalDebt: number;
    avgRate: number;
    monthlyRepayments: number;
  };
}

const PAGE_HEIGHT = 280;
const MARGIN_LEFT = 20;
const MARGIN_RIGHT = 170;

function checkNewPage(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_HEIGHT) {
    doc.addPage();
    return 20;
  }
  return y;
}

function addFooter(doc: jsPDF, generatedDate: string): void {
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by BrickTrack on ${generatedDate}`, MARGIN_LEFT, 290);
    doc.text(`Page ${i} of ${pageCount}`, MARGIN_RIGHT, 290, {
      align: "right",
    });
    doc.setTextColor(0, 0, 0);
  }
}

function addSectionHeader(doc: jsPDF, title: string, y: number): number {
  y = checkNewPage(doc, y, 15);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, MARGIN_LEFT, y);
  y += 3;
  doc.setLineWidth(0.5);
  doc.line(MARGIN_LEFT, y, MARGIN_RIGHT, y);
  y += 8;
  return y;
}

function addIncomeExpenses(
  doc: jsPDF,
  data: TaxReportData,
  y: number
): number {
  y = addSectionHeader(doc, "Income & Expenses", y);

  for (const prop of data.properties) {
    y = checkNewPage(doc, y, 40);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(
      `${prop.property.address}, ${prop.property.suburb} ${prop.property.state}`,
      MARGIN_LEFT,
      y
    );
    y += 7;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");

    // Income items
    const incomeItems = prop.atoBreakdown.filter(
      (item) => !item.isDeductible && item.amount > 0
    );
    if (incomeItems.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.text("Income", MARGIN_LEFT + 5, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      for (const item of incomeItems) {
        y = checkNewPage(doc, y, 6);
        const ref = item.atoReference ?? "";
        if (ref) {
          doc.setFont("helvetica", "bold");
          doc.text(ref, MARGIN_LEFT + 10, y);
          doc.setFont("helvetica", "normal");
        }
        doc.text(item.label, MARGIN_LEFT + 25, y);
        doc.text(formatCurrencyWithCents(item.amount), MARGIN_RIGHT, y, {
          align: "right",
        });
        y += 5;
      }
      y += 3;
    }

    // Deduction items sorted by ATO D-number
    const deductionItems = prop.atoBreakdown
      .filter((item) => item.isDeductible && item.amount !== 0)
      .sort((a, b) => {
        const aNum = parseInt(a.atoReference?.replace("D", "") ?? "99");
        const bNum = parseInt(b.atoReference?.replace("D", "") ?? "99");
        return aNum - bNum;
      });
    if (deductionItems.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.text("Deductions", MARGIN_LEFT + 5, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      for (const item of deductionItems) {
        y = checkNewPage(doc, y, 6);
        const ref = item.atoReference ?? "";
        doc.setFont("helvetica", "bold");
        doc.text(ref, MARGIN_LEFT + 10, y);
        doc.setFont("helvetica", "normal");
        doc.text(item.label, MARGIN_LEFT + 25, y);
        doc.text(
          formatCurrencyWithCents(Math.abs(item.amount)),
          MARGIN_RIGHT,
          y,
          { align: "right" }
        );
        y += 5;
      }
      y += 3;
    }

    // Property subtotals
    y = checkNewPage(doc, y, 20);
    doc.line(MARGIN_LEFT + 5, y, MARGIN_RIGHT, y);
    y += 5;
    doc.setFont("helvetica", "bold");
    doc.text("Total Income:", MARGIN_LEFT + 10, y);
    doc.text(
      formatCurrencyWithCents(prop.metrics.totalIncome),
      MARGIN_RIGHT,
      y,
      { align: "right" }
    );
    y += 5;
    doc.text("Total Deductions:", MARGIN_LEFT + 10, y);
    doc.text(
      formatCurrencyWithCents(prop.metrics.totalDeductible),
      MARGIN_RIGHT,
      y,
      { align: "right" }
    );
    y += 5;
    const netLabel =
      prop.metrics.netIncome >= 0 ? "Net Rental Income:" : "Net Rental Loss:";
    doc.text(netLabel, MARGIN_LEFT + 10, y);
    doc.text(
      formatCurrencyWithCents(prop.metrics.netIncome),
      MARGIN_RIGHT,
      y,
      { align: "right" }
    );
    y += 12;
  }

  // Portfolio totals
  y = checkNewPage(doc, y, 25);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Portfolio Totals", MARGIN_LEFT, y);
  y += 7;
  doc.setFontSize(10);
  doc.text(
    `Total Income: ${formatCurrencyWithCents(data.totals.totalIncome)}`,
    MARGIN_LEFT + 5,
    y
  );
  y += 6;
  doc.text(
    `Total Deductions: ${formatCurrencyWithCents(data.totals.totalDeductible)}`,
    MARGIN_LEFT + 5,
    y
  );
  y += 6;
  doc.text(
    `Net Result: ${formatCurrencyWithCents(data.totals.netIncome)}`,
    MARGIN_LEFT + 5,
    y
  );
  y += 12;

  // Per-property summary table (only when 2+ properties)
  if (data.properties.length > 1) {
    y = checkNewPage(doc, y, 15 + data.properties.length * 6);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Net Rental Income Summary", MARGIN_LEFT, y);
    y += 7;

    // Header
    doc.setFontSize(8);
    doc.text("Property", MARGIN_LEFT + 5, y);
    doc.text("Income", 95, y, { align: "right" });
    doc.text("Deductions", 125, y, { align: "right" });
    doc.text("Net Result", MARGIN_RIGHT, y, { align: "right" });
    y += 1;
    doc.line(MARGIN_LEFT + 5, y, MARGIN_RIGHT, y);
    y += 4;

    doc.setFont("helvetica", "normal");
    for (const prop of data.properties) {
      y = checkNewPage(doc, y, 6);
      const label = `${prop.property.suburb} ${prop.property.state}`;
      doc.text(label, MARGIN_LEFT + 5, y);
      doc.text(formatCurrencyWithCents(prop.metrics.totalIncome), 95, y, {
        align: "right",
      });
      doc.text(formatCurrencyWithCents(prop.metrics.totalDeductible), 125, y, {
        align: "right",
      });
      doc.text(formatCurrencyWithCents(prop.metrics.netIncome), MARGIN_RIGHT, y, {
        align: "right",
      });
      y += 5;
    }

    // Totals row
    y += 1;
    doc.line(MARGIN_LEFT + 5, y, MARGIN_RIGHT, y);
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.text("Total", MARGIN_LEFT + 5, y);
    doc.text(formatCurrencyWithCents(data.totals.totalIncome), 95, y, {
      align: "right",
    });
    doc.text(formatCurrencyWithCents(data.totals.totalDeductible), 125, y, {
      align: "right",
    });
    doc.text(formatCurrencyWithCents(data.totals.netIncome), MARGIN_RIGHT, y, {
      align: "right",
    });
    y += 10;
  }

  return y;
}

function addDepreciation(
  doc: jsPDF,
  data: MyTaxReportData,
  y: number
): number {
  y = addSectionHeader(doc, "Depreciation Schedule", y);

  for (const prop of data.properties) {
    if (
      prop.depreciation.capitalWorks === 0 &&
      prop.depreciation.plantEquipment === 0
    )
      continue;

    y = checkNewPage(doc, y, 25);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(
      `${prop.address}, ${prop.suburb} ${prop.state}`,
      MARGIN_LEFT,
      y
    );
    y += 7;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    if (prop.depreciation.capitalWorks > 0) {
      doc.text("[D14] Capital Works (Div 43)", MARGIN_LEFT + 5, y);
      doc.text(
        formatCurrencyWithCents(prop.depreciation.capitalWorks),
        MARGIN_RIGHT,
        y,
        { align: "right" }
      );
      y += 5;
    }
    if (prop.depreciation.plantEquipment > 0) {
      doc.text("Plant & Equipment (Div 40)", MARGIN_LEFT + 5, y);
      doc.text(
        formatCurrencyWithCents(prop.depreciation.plantEquipment),
        MARGIN_RIGHT,
        y,
        { align: "right" }
      );
      y += 5;
    }
    y += 8;
  }

  return y;
}

function addCapitalGains(
  doc: jsPDF,
  data: CgtPropertyResult[],
  y: number
): number {
  y = addSectionHeader(doc, "Capital Gains Tax", y);

  if (data.length === 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.text("No properties sold in this financial year.", MARGIN_LEFT, y);
    y += 10;
    return y;
  }

  for (const prop of data) {
    y = checkNewPage(doc, y, 40);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(prop.propertyAddress, MARGIN_LEFT, y);
    y += 7;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(`Purchased: ${prop.purchaseDate}`, MARGIN_LEFT + 5, y);
    y += 5;
    doc.text(`Sold: ${prop.saleDate}`, MARGIN_LEFT + 5, y);
    y += 5;
    doc.text(
      `Cost Base: ${formatCurrencyWithCents(prop.costBase)}`,
      MARGIN_LEFT + 5,
      y
    );
    y += 5;
    doc.text(
      `Sale Price: ${formatCurrencyWithCents(prop.salePrice)}`,
      MARGIN_LEFT + 5,
      y
    );
    y += 5;
    doc.text(
      `Capital Gain: ${formatCurrencyWithCents(prop.capitalGain)}`,
      MARGIN_LEFT + 5,
      y
    );
    y += 5;
    if (prop.heldOverTwelveMonths) {
      doc.setFont("helvetica", "bold");
      doc.text(
        `Discounted Gain (50%): ${formatCurrencyWithCents(prop.discountedGain)}`,
        MARGIN_LEFT + 5,
        y
      );
      y += 5;
    }
    y += 8;
  }

  return y;
}

function addTaxPosition(
  doc: jsPDF,
  data: TaxPositionData,
  y: number
): number {
  y = addSectionHeader(doc, "Tax Position Summary", y);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  const lines: [string, string][] = [
    ["Taxable Income", formatCurrencyWithCents(data.taxableIncome)],
    ["Base Tax", formatCurrencyWithCents(data.baseTax)],
    ["Medicare Levy", formatCurrencyWithCents(data.medicareLevy)],
  ];

  if (data.medicareLevySurcharge > 0) {
    lines.push([
      "Medicare Levy Surcharge",
      formatCurrencyWithCents(data.medicareLevySurcharge),
    ]);
  }
  if (data.hecsRepayment > 0) {
    lines.push([
      "HECS/HELP Repayment",
      formatCurrencyWithCents(data.hecsRepayment),
    ]);
  }
  lines.push(
    ["Total Tax Liability", formatCurrencyWithCents(data.totalTaxLiability)],
    ["PAYG Withheld", formatCurrencyWithCents(data.paygWithheld)]
  );

  for (const [label, value] of lines) {
    y = checkNewPage(doc, y, 6);
    doc.text(label, MARGIN_LEFT + 5, y);
    doc.text(value, MARGIN_RIGHT, y, { align: "right" });
    y += 6;
  }

  y += 3;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  const resultLabel = data.isRefund
    ? "Estimated Refund:"
    : "Estimated Owing:";
  doc.text(resultLabel, MARGIN_LEFT + 5, y);
  doc.text(
    formatCurrencyWithCents(Math.abs(data.refundOrOwing)),
    MARGIN_RIGHT,
    y,
    { align: "right" }
  );
  y += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Marginal Rate: ${(data.marginalRate * 100).toFixed(1)}%`,
    MARGIN_LEFT + 5,
    y
  );
  y += 5;
  doc.text(
    `Property Tax Savings: ${formatCurrencyWithCents(data.propertySavings)}`,
    MARGIN_LEFT + 5,
    y
  );
  y += 12;

  return y;
}

function addPortfolioOverview(
  doc: jsPDF,
  data: PortfolioSnapshotData,
  y: number
): number {
  y = addSectionHeader(doc, "Portfolio Overview", y);

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`${data.totals.propertyCount} Properties`, MARGIN_LEFT, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  for (const prop of data.properties) {
    y = checkNewPage(doc, y, 20);
    doc.setFontSize(9);
    doc.text(
      `${prop.address}, ${prop.suburb} ${prop.state}`,
      MARGIN_LEFT + 5,
      y
    );
    y += 5;
    doc.text(
      `Value: ${formatCurrencyWithCents(prop.currentValue)}  |  Equity: ${formatCurrencyWithCents(prop.equity)}  |  LVR: ${(prop.lvr * 100).toFixed(1)}%`,
      MARGIN_LEFT + 10,
      y
    );
    y += 7;
  }

  y += 3;
  doc.line(MARGIN_LEFT, y, MARGIN_RIGHT, y);
  y += 5;
  doc.setFont("helvetica", "bold");
  doc.text(
    `Total Value: ${formatCurrencyWithCents(data.totals.totalValue)}`,
    MARGIN_LEFT + 5,
    y
  );
  y += 6;
  doc.text(
    `Total Debt: ${formatCurrencyWithCents(data.totals.totalDebt)}`,
    MARGIN_LEFT + 5,
    y
  );
  y += 6;
  doc.text(
    `Total Equity: ${formatCurrencyWithCents(data.totals.totalEquity)}`,
    MARGIN_LEFT + 5,
    y
  );
  y += 6;
  doc.text(
    `Average LVR: ${(data.totals.avgLvr * 100).toFixed(1)}%`,
    MARGIN_LEFT + 5,
    y
  );
  y += 12;

  return y;
}

function addLoanDetails(
  doc: jsPDF,
  data: LoanPackSnapshotData,
  y: number
): number {
  y = addSectionHeader(doc, "Loan Details", y);

  for (const prop of data.properties) {
    y = checkNewPage(doc, y, 25);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(prop.address, MARGIN_LEFT, y);
    y += 7;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    for (const loan of prop.loans) {
      y = checkNewPage(doc, y, 12);
      doc.text(
        `${loan.lender} — ${loan.type}`,
        MARGIN_LEFT + 5,
        y
      );
      y += 5;
      doc.text(
        `Balance: ${formatCurrencyWithCents(loan.balance)}  |  Rate: ${loan.rate.toFixed(2)}%  |  Repayment: ${formatCurrencyWithCents(loan.monthlyRepayment)}/mo`,
        MARGIN_LEFT + 10,
        y
      );
      y += 7;
    }
    y += 3;
  }

  doc.line(MARGIN_LEFT, y, MARGIN_RIGHT, y);
  y += 5;
  doc.setFont("helvetica", "bold");
  doc.text(
    `Total Debt: ${formatCurrencyWithCents(data.totals.totalDebt)}`,
    MARGIN_LEFT + 5,
    y
  );
  y += 6;
  doc.text(
    `Avg Rate: ${data.totals.avgRate.toFixed(2)}%`,
    MARGIN_LEFT + 5,
    y
  );
  y += 6;
  doc.text(
    `Monthly Repayments: ${formatCurrencyWithCents(data.totals.monthlyRepayments)}`,
    MARGIN_LEFT + 5,
    y
  );
  y += 12;

  return y;
}

/**
 * Generate accountant pack PDF. Returns ArrayBuffer suitable for:
 * - Client-side: `new Blob([result], { type: "application/pdf" })` for download
 * - Server-side: `Buffer.from(result)` for Resend attachment
 */
export function generateAccountantPackPDF(
  config: AccountantPackConfig
): ArrayBuffer {
  const doc = new jsPDF();
  let y = 20;
  const generatedDate = new Date().toLocaleDateString("en-AU", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  // --- Cover Page ---
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Accountant Pack", MARGIN_LEFT, y);
  y += 10;

  doc.setFontSize(16);
  doc.text(
    `FY${config.financialYear - 1}-${String(config.financialYear).slice(-2)}`,
    MARGIN_LEFT,
    y
  );
  y += 12;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Prepared by: ${config.userName}`, MARGIN_LEFT, y);
  y += 6;
  if (config.accountantName) {
    doc.text(`Prepared for: ${config.accountantName}`, MARGIN_LEFT, y);
    y += 6;
  }
  doc.text(`Generated: ${generatedDate}`, MARGIN_LEFT, y);
  y += 12;

  // Table of contents
  const enabledSections: string[] = [];
  if (config.sections.incomeExpenses)
    enabledSections.push("Income & Expenses");
  if (config.sections.depreciation)
    enabledSections.push("Depreciation Schedule");
  if (config.sections.capitalGains)
    enabledSections.push("Capital Gains Tax");
  if (config.sections.taxPosition)
    enabledSections.push("Tax Position Summary");
  if (config.sections.portfolioOverview)
    enabledSections.push("Portfolio Overview");
  if (config.sections.loanDetails) enabledSections.push("Loan Details");

  if (enabledSections.length > 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Contents", MARGIN_LEFT, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    for (const section of enabledSections) {
      doc.text(`\u2022 ${section}`, MARGIN_LEFT + 5, y);
      y += 6;
    }
  }

  y += 10;
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text(
    "This is a reference document generated by BrickTrack. It is not an official ATO submission.",
    MARGIN_LEFT,
    y
  );

  y += 5;
  doc.text("Prepared using BrickTrack — bricktrack.au", MARGIN_LEFT, y);

  // --- Content Pages ---
  if (config.sections.incomeExpenses && config.data.taxReport) {
    doc.addPage();
    y = 20;
    y = addIncomeExpenses(doc, config.data.taxReport, y);
  }

  if (config.sections.depreciation && config.data.myTaxReport) {
    doc.addPage();
    y = 20;
    y = addDepreciation(doc, config.data.myTaxReport, y);
  }

  if (config.sections.capitalGains && config.data.cgtData) {
    doc.addPage();
    y = 20;
    y = addCapitalGains(doc, config.data.cgtData, y);
  }

  if (config.sections.taxPosition && config.data.taxPosition) {
    doc.addPage();
    y = 20;
    y = addTaxPosition(doc, config.data.taxPosition, y);
  }

  if (config.sections.portfolioOverview && config.data.portfolioSnapshot) {
    doc.addPage();
    y = 20;
    y = addPortfolioOverview(doc, config.data.portfolioSnapshot, y);
  }

  if (config.sections.loanDetails && config.data.loanPackSnapshot) {
    doc.addPage();
    y = 20;
    y = addLoanDetails(doc, config.data.loanPackSnapshot, y);
  }

  // Add footer to all pages
  addFooter(doc, generatedDate);

  return doc.output("arraybuffer") as ArrayBuffer;
}
