import jsPDF from "jspdf";
import type { LoanPackSnapshot } from "@/server/services/loanPack";

const formatCurrency = (amount: number): string =>
  new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD", maximumFractionDigits: 0 }).format(amount);

const formatPercent = (value: number): string => `${value.toFixed(1)}%`;

export function generateLoanPackPDF(data: LoanPackSnapshot): Blob {
  const doc = new jsPDF();
  let y = 20;

  // Title
  doc.setFontSize(20);
  doc.text("Loan Application Pack", 20, y);
  y += 10;

  // Generated info
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated for ${data.userName} on ${new Date(data.generatedAt).toLocaleDateString("en-AU")}`, 20, y);
  doc.setTextColor(0, 0, 0);
  y += 15;

  // Portfolio Summary
  doc.setFontSize(14);
  doc.text("Portfolio Summary", 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.text(`Total Value: ${formatCurrency(data.portfolio.totals.totalValue)}`, 20, y); y += 6;
  doc.text(`Total Debt: ${formatCurrency(data.portfolio.totals.totalDebt)}`, 20, y); y += 6;
  doc.text(`Total Equity: ${formatCurrency(data.portfolio.totals.totalEquity)}`, 20, y); y += 6;
  doc.text(`Average LVR: ${formatPercent(data.portfolio.totals.avgLvr)}`, 20, y); y += 15;

  // Properties
  doc.setFontSize(14);
  doc.text(`Properties (${data.portfolio.properties.length})`, 20, y);
  y += 10;

  for (const property of data.portfolio.properties) {
    if (y > 240) { doc.addPage(); y = 20; }

    doc.setFontSize(11);
    doc.text(property.address, 20, y); y += 5;
    doc.setFontSize(9);
    doc.text(`${property.suburb}, ${property.state} ${property.postcode}`, 20, y); y += 6;

    doc.text(`Value: ${formatCurrency(property.currentValue)} | Equity: ${formatCurrency(property.equity)} | LVR: ${formatPercent(property.lvr)}`, 25, y); y += 5;
    doc.text(`Purchase: ${formatCurrency(property.purchasePrice)} on ${property.purchaseDate}`, 25, y); y += 5;

    if (property.loans.length > 0) {
      for (const loan of property.loans) {
        doc.text(`Loan: ${loan.lender} - ${formatCurrency(loan.balance)} @ ${loan.rate}%`, 30, y); y += 5;
      }
    }
    y += 5;
  }

  // Page 2: Financials
  doc.addPage();
  y = 20;

  // Income
  doc.setFontSize(14);
  doc.text("Income", 20, y); y += 10;
  doc.setFontSize(10);
  doc.text(`Monthly Rent: ${formatCurrency(data.income.monthlyRent)}`, 20, y); y += 6;
  doc.text(`Annual Rent: ${formatCurrency(data.income.annualRent)}`, 20, y); y += 10;

  for (const item of data.income.byProperty) {
    doc.setFontSize(9);
    doc.text(`${item.address}: ${formatCurrency(item.monthlyRent)}/mo`, 25, y); y += 5;
  }
  y += 10;

  // Expenses
  doc.setFontSize(14);
  doc.text("Expenses", 20, y); y += 10;
  doc.setFontSize(10);
  doc.text(`Monthly Average: ${formatCurrency(data.expenses.totalMonthly)}`, 20, y); y += 6;
  doc.text(`Annual Total: ${formatCurrency(data.expenses.totalAnnual)}`, 20, y); y += 10;

  for (const cat of data.expenses.categories) {
    doc.setFontSize(9);
    doc.text(`${cat.name}: ${formatCurrency(cat.annual)}/yr`, 25, y); y += 5;
  }
  y += 10;

  // Cash Flow
  doc.setFontSize(14);
  doc.text("Cash Flow", 20, y); y += 10;
  doc.setFontSize(10);
  doc.text(`Monthly Net: ${formatCurrency(data.cashFlow.monthlyNet)}`, 20, y); y += 6;
  doc.text(`Annual Net: ${formatCurrency(data.cashFlow.annualNet)}`, 20, y); y += 15;

  // Compliance
  if (data.compliance.items.length > 0) {
    if (y > 220) { doc.addPage(); y = 20; }
    doc.setFontSize(14);
    doc.text("Compliance Status", 20, y); y += 10;
    doc.setFontSize(10);
    doc.text(`Compliant: ${data.compliance.summary.compliant} | Upcoming: ${data.compliance.summary.upcoming} | Overdue: ${data.compliance.summary.overdue}`, 20, y); y += 8;

    for (const item of data.compliance.items.slice(0, 10)) {
      doc.setFontSize(9);
      doc.text(`${item.property} - ${item.type}: ${item.status}`, 25, y); y += 5;
    }
    y += 10;
  }

  // Milestones
  if (data.milestones.length > 0) {
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setFontSize(14);
    doc.text("Milestones Achieved", 20, y); y += 10;

    for (const m of data.milestones.slice(0, 10)) {
      doc.setFontSize(9);
      doc.text(`${m.property} - ${m.formattedValue} (${new Date(m.achievedAt).toLocaleDateString("en-AU")})`, 25, y); y += 5;
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by BrickTrack - propertytracker.com.au", 20, 285);

  return doc.output("blob");
}
