import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - BrickTrack",
  description: "Terms and conditions for using BrickTrack.",
};

export default function TermsPage() {
  return (
    <main className="py-12 md:py-20 px-4">
      <div className="container mx-auto max-w-3xl prose prose-neutral dark:prose-invert">
        <h1>Terms of Service</h1>
        <p className="lead">Last updated: February 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using BrickTrack, you agree to be bound by these Terms of
          Service. If you do not agree, do not use our service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          BrickTrack is a property portfolio management platform that helps Australian
          investors track their properties, connect bank accounts, categorise transactions,
          and generate reports for tax purposes.
        </p>

        <h2>3. Account Registration</h2>
        <p>
          You must provide accurate information when creating an account. You are responsible
          for maintaining the security of your account credentials and for all activities
          under your account.
        </p>

        <h2>4. Subscription and Billing</h2>
        <ul>
          <li>Free tier: Limited to 1 property with basic features</li>
          <li>Paid plans: Billed monthly or annually as selected</li>
          <li>Cancel anytime; access continues until the end of your billing period</li>
          <li>Refunds are provided at our discretion</li>
        </ul>

        <h2>5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the service for any unlawful purpose</li>
          <li>Attempt to gain unauthorized access to our systems</li>
          <li>Interfere with other users&apos; use of the service</li>
          <li>Upload malicious content</li>
          <li>Resell or redistribute the service without permission</li>
        </ul>

        <h2>6. Data Accuracy</h2>
        <p>
          BrickTrack provides tools to help you manage your property portfolio.
          We do not guarantee the accuracy of data imported from banks or other sources.
          You are responsible for verifying the accuracy of your data and reports.
        </p>

        <h2>7. Tax Advice Disclaimer</h2>
        <p>
          BrickTrack is not a tax advisor. Reports generated by our service are for
          informational purposes only and should not be considered tax advice. Always
          consult a qualified tax professional for advice specific to your situation.
        </p>

        <h2>8. Intellectual Property</h2>
        <p>
          BrickTrack and its content, features, and functionality are owned by us
          and are protected by copyright, trademark, and other intellectual property laws.
        </p>

        <h2>9. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, BrickTrack shall not be liable for
          any indirect, incidental, special, consequential, or punitive damages, including
          loss of profits, data, or other intangible losses.
        </p>

        <h2>10. Termination</h2>
        <p>
          We may terminate or suspend your account at any time for violations of these terms.
          You may cancel your account at any time through your account settings.
        </p>

        <h2>11. Changes to Terms</h2>
        <p>
          We may modify these terms at any time. We will notify you of material changes
          via email or in-app notification. Continued use after changes constitutes
          acceptance of the new terms.
        </p>

        <h2>12. Governing Law</h2>
        <p>
          These terms are governed by the laws of Australia. Any disputes shall be
          resolved in the courts of New South Wales, Australia.
        </p>

        <h2>13. Contact</h2>
        <p>
          For questions about these terms, contact us at{" "}
          <a href="mailto:legal@bricktrack.au">legal@bricktrack.au</a>.
        </p>
      </div>
    </main>
  );
}
